services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: ".env"
    ports:
      - 9091:9091 # Transmission
      - 7878:7878 # Radarr
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 8191:8191 # Flaresolver
      - 8112:8112 # Deluge
       
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NP
    volumes:
      - ./container_data/container_data/radarr/config:/config
      - ./container_data/radarr/movies:/movies
      - ./container_data/radarr/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NP
    volumes:
      - ./container_data/prowlarr/config:/config
    restart: unless-stopped
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NP
    volumes:
      - ./container_data/sonarr/config:/config
      - ./container_data/sonarr/tv_shows:/tv_shows
      - ./container_data/sonarr/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  flaresolver:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolver
    environment:
      - LOG_LEVEL=info
    volumes:
      - ./container_data/flaresolverr/config:/config
    restart: unless-stopped
    network_mode: service:gluetun

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NP
    volumes:
      - ./container_data/transmission/config:/config
      - ./container_data/transmission/watch:/watch
      - ./container_data/transmission/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NP
    volumes:
      - ./container_data/deluge/config:/config
      - ./container_data/deluge/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
